# Generated by Django 5.1.6 on 2025-02-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Viewer', 'Viewer'), ('Editor', 'Editor'), ('Empleado', 'Empleado')], default='Viewer', max_length=20),
        ),
    ]
