# Generated by Django 5.1.6 on 2025-02-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la flor')),
                ('descripcion', models.TextField(verbose_name='Descripción de la flor')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(verbose_name='Cantidad en stock')),
            ],
            options={
                'verbose_name': 'Flor',
                'verbose_name_plural': 'Flores',
            },
        ),
    ]
